In [1]:
import pandas as pd

data = pd.read_csv('philippine_file.csv')
data

,educations-end_date,educations-field_of_study,educations-school-name,positions-is-current,num-connections,industry-specialization
0,31/12/2013,16,NEW NORTHERN MINDANAO COLLEGES,0,0,5
1,31/12/2012,16,CENTRAL PHILIPPINE UNIVERSITY,1,3,6
2,31/12/2006,0,INTERNATIONAL CORRESPONDENCE SCHOOLS,0,11,16
3,31/12/1987,6,UNIVERSITY OF THE PHILIPPINES,0,36,4
4,31/12/1994,0,POLYTECHNIC UNIVERSITY OF THE PHILIPPINES,1,0,0
5,31/12/2002,16,UNIVERSITY OF THE PHILIPPINES,0,5,5
6,31/12/2008,16,DE LA SALLE UNIVERSITY,1,6,5
7,31/12/2009,4,UNIVERSITY OF THE PHILIPPINES,0,0,4
8,31/12/2006,4,DAVAO DEL NORTE STATE COLLEGE,0,8,4
9,31/12/2007,2,INFORMATICS COMPUTER INSTITUTE,0,6,4
10,31/12/1994,16,"ST. PAUL'S COLLEGE, QUEZON CITY",1,1,1
11,31/12/2001,2,UNIVERSITY OF THE EAST,0,31,13
12,31/12/1978,16,UNIVERSITY OF SAN JOSE - RECOLETOS,1,1,4
13,31/12/2007,12,UNIVERSITY OF THE PHILIPPINES,1,1,16
14,31/12/2003,1,THE NATIONAL TEACHERS COLLEGE,0,0,5
15,31/12/2012,10,LYCEUM OF THE PHILIPPINES UNIVERSITY - BATANGAS,1,2,10
16,31/12/2003,16,ATENEO DE NAGA UNIVERSITY,0,1,7
17,31/12/2003,6,AMA UNIVERSITY,0,28,4
18,31/12/1991,0,ATENEO DE DAVAO UNIVERSITY,1,31,16
19,31/12/2002,10,SAINT LOUIS UNIVERSITY (PH),0,217,16
20,31/12/2011,16,UNIVERSITY OF THE PHILIPPINES,0,27,0
21,31/12/2004,16,PAMANTASAN NG LUNGSOD NG PASAY,0,10,0
22,31/12/2002,2,DE LA SALLE - COLLEGE OF ST. BENILDE,0,96,4
23,31/12/2009,6,SAINT JOSEPH INSTITUTE OF TECHNOLOGY,1,5,4
24,31/12/1992,16,SAN SEBASTIAN COLLEGE,1,6,8
25,31/12/2009,4,MINDANAO STATE UNIVERSITY,0,20,4
26,31/12/2014,10,UNIVERSITY OF SAINT ANTHONY,0,0,9
27,31/12/2009,4,UNIVERSITY OF SAN JOSE RECOLLETOS,0,20,4
28,31/12/2008,16,CEBU NORMAL UNIVERSITY,0,0,4
29,31/12/1995,16,ADAMSON UNIVERSITY,1,76,8
...,...,...,...,...,...,...
2110,31/12/2008,10,GRADUATE SCHOOL COLLEGE OF BUSINESS DE LA SALL...,1,115,10
2111,31/12/2011,14,LYCEUM OF THE PHILIPPINES UNIVERSITY,0,13,16
2112,31/12/2005,16,UNIVERSITY OF SAINT LA SALLE,0,397,0
2113,31/12/2007,16,POLYTECHNIC UNIVERSITY OF THE PHILIPPINES,1,19,0
2114,31/12/2012,4,AMA UNIVERSITY,1,3,4
2115,31/12/2003,4,CENTER FOR INDUSTRIAL TECHNOLOGY AND ENTERPRISE,0,221,4
2116,31/12/2000,4,DE LA SALLE UNIVERSITY,0,500+,4
2117,31/12/1991,16,UNIVERSITY OF SAN CARLOS,1,3,7
2118,31/12/1998,6,ADAMSON UNIVERSITY,0,500+,16
2119,31/12/2009,16,RIZAL TECHNOLOGICAL UNIVERSITY,1,33,1
2120,31/12/2000,16,FAR EASTERN UNIVERSITY,0,500+,1
2121,31/12/2008,16,SOUTH EAST ASIA GRADUATE SCHOOL OF THEOLOGY,1,40,5
2122,31/12/2008,5,FEU/METROPOLITAN HOSPITAL COLLEGE OF NURSING,0,1,7
2123,31/12/2011,16,ATENEO GRADUATE SCHOOL OF BUSINESS,1,500+,16
2124,31/12/1987,16,THE UNIVERSITY OF DALLAS,0,8,15
2125,31/12/2002,4,AMA COMPUTER COLLEGE - DAVAO,0,2,16
2126,31/12/2011,16,UNIVERSITY OF SAN CARLOS,0,2,16
2127,31/12/2000,4,EASTERN SAMAR STATE UNIVERSITY,0,2,2
2128,31/12/2010,10,DE LA SALLE UNIVERSITY DAMARINAS,1,9,10
2129,31/12/1996,16,SAINT JOSEPH INSTITUTE OF TECHNOLOGY,1,0,5
2130,31/12/2007,1,COMPUTER ARTS AND TECHNOLOGICAL COLLEGE,0,11,2
2131,31/12/2006,14,ATENEO DE MANILA UNIVERSITY,0,57,14
2132,31/12/2002,16,GOLDEN GATE COLLEGES,1,19,16
2133,31/12/1992,16,UNIVERSITY OF NUEVA CACERES,0,9,0
2134,31/12/1996,16,COLEGIO DE SAN JUAN DE LETRAN,0,43,0
2135,31/12/2011,16,SURIGAO STATE COLLEGE OF TECHNOLOGY,0,1,4
2136,31/12/2005,16,CEBU DOCTORS' UNIVERSITY,0,9,4
2137,31/12/1995,16,BICOL UNIVERSITY,0,0,0
2138,31/12/2008,14,ATENEO DE MANILA UNIVERSITY,1,52,14
2139,31/12/2009,4,PAMANTASAN NG LUNGSOD NG MAYNILA,1,16,4